# Delete Later

## Assessment Task

Students are advised to review and adhere to the submission requirements documented after the
assessment task.

Scenario:

“Today, big data is ubiquitous, machine learning applications are thriving, artificial intelligence appears in
everyday conversations, and the internet of things is present even in household appliances. Businesses and
organizations are increasingly managed through cloud computing and high performance computing is
progressively accessible as a service…More effective operations, reduced uncertainties, and real time
decision-support could revolutionize agriculture to a great extent . Food could be produced more efficiently,
of higher nutritional quality, in more stable supplies, with less environmental damage, and likely with
additional economic, social, and ecological benefits.”(Sjoukje A. Osinga, Dilli Paudel, Spiros A. Mouzakitis,
Ioannis N. Athanasiadis (2022))

You have been tasked with analysing Ireland's Agricultural data and comparing the Irish Agri sector with
other countries worldwide. This analysis should also include forecasting, sentiment analysis and evidence
based recommendations for the sector as well as a complete rationale of the entire process used to
discover your findings. Your Research could include export, import, trade imbalance, arable production,
animal stock, medicinal input, organic, gm products etc. (or any other relevant topic EXCEPT Climate
change) with Ireland as your base line.

Note:
- While topical, Agricultural impact on Climate Change SHOULD NOT be chosen as an area of research for this assessment.
- Members of the European Union implement the Common Agricultural Policy and this should be researched as it has a significant statistical impact.
- The United Kingdom is NOT part of the European Union

You must source appropriate data sets from any available repository to inform your research (all datasets MUST be referenced and the relevant licence/permissions detailed).

### Criteria of Analysis

Discuss the choice of project management framework you have deemed suitable for this project.
It is expected that you use some type of version control software eg: GitHub, Gitlab, BitBucket etc with regular commits of code and report versions. Please include the address of your version control repository in your report.

### Programming for DA Tasks [0-100]
- The project must be explored programmatically, this means that you must implement suitable Python tools (code and/or libraries) to complete the analysis required. All of this is to be implemented in a Jupyter Notebook.[0-50]
- The project documentation must include sound justifications and explanation of your code choices. (code quality standards should also be applied) [0-50]

Total Mark = 50+50=100:(100\*0.5=50%)

### Statistics for Data Analytics Tasks
- Use descriptive statistics and appropriate visualisations in order to summarise the dataset(s) used, and to help justify the chosen models. [0-20]
- Analyse the variables in your dataset(s) and use appropriate inferential statistics to gain insights on possible population values (e.g., if you were working with international commerce, you could find a confidence interval for the population proportion of yearly dairy exports out of all agricultural exports). [0-20]
- Undertake research to find similarities between some country(s) against Ireland, and apply parametric and non-parametric inferential statistical techniques to compare them (e.g., t-test, analysis of variance, Wilcoxon test, chi-squared test, among others). You must justify your choices and verify the applicability of the tests. Hypotheses and conclusions must be clearly stated. You are expected to use at least 5 different inferential statistics tests. [0-40]
- Use the outcome of your analysis to deepen your research. Indicate the challenges you faced in the process. [0-20]

Note: All your calculations and reasoning behind your models must be documented in the report and/or the appendix.
Total Mark = 20+20+40+20=100:(100\*0.5=50%)

### Machine Learning Tasks
Use of multiple models (at least two) to compare and contrast results and insights gained.
- Describe the rationale and justification for the choice of machine learning models for the above-mentioned scenario. Machine Learning models can be used for Prediction, Classification, Clustering, sentiment analysis, recommendation systems and Time series analysis. You should plan on trying multiple approaches (at least two) with proper selection of hyperparameters using GridSearchCV method. You can choose appropriate features from the datasets and a target feature to answer the question asked in the scenario in the case of supervised learning. [0 - 30]
- Collect and develop a dataset based on the agriculture topic related to Ireland as well as other parts of the world. Perform a sentimental analysis for an appropriate agricultural topic (e.g., product price, feed quality etc…) for producers and consumers point of view in Ireland. [0 - 25]
- You should train and test for Supervised Learning and other appropriate metrics for unsupervised/semi-supervised machine learning models that you have chosen. Use cross validation to provide authenticity of the modelling outcomes. You can apply dimensionality reduction methods to prepare the dataset based on your machine learning modelling requirements. [0 - 30]
- A Table or graphics should be provided to illustrate the similarities and contrast of the Machine Learning modelling outcomes based on the scoring metric used for the analysis of the above-mentioned scenario. Discuss and elaborate your understanding clearly. [0 - 15]

Total Mark = 30+25+30+15=100:(100\*0.5=50%)

### Data Preparation & Visualisation Tasks
- Discuss in detail the process of acquiring your raw data, detailing the positive and/or negative aspects of your research and acquisition . This should include the relevance and implications of any and all licensing/permissions associated with the data. [0-15]
- Exploratory Data Analysis helps to identify patterns, inconsistencies, anomalies, missing data, and other attributes and issues in data sets so problems can be addressed. Evaluate your raw data and detail, in depth, the various attributes and issues that you find. Your evaluation should reference evidence to support your chosen methodology and use visualizations to illustrate your findings. [0-
25]
- Taking into consideration the tasks required in the machine learning section, use appropriate data cleaning, engineering, extraction and/or other techniques to structure and enrich your data. Rationalize your decisions and implementation, including evidence of how your process has addressed the problems identified in the EDA (Exploratory Data Analysis) stage and how your structured data will assist in the analysis stage. This should include visualizations to illustrate your work and evidence to support your methodology.[0-30]
- Modern farming has a great dependence on technology and relies upon visualizations to communicate information, this includes web based, mobile based and many other digital transmission formats. Develop an interactive dashboard tailored to modern farmers, using tufts principles, to showcase the information/evidence gathered following your Machine Learning Analysis. Detail the rationale for approach and visualisation choices made during development. Note you may not use Powerbi, rapidminer, tableau or other such tools to accomplish this (at this stage).[0-30]

Total Mark = 15+25+30+30=100:(100\*0.5=50%)

### Additional notes :
All:
- Your documentation should present your approach to the project, including elements of project planning ( timelines).
- Ensure that your documentation follows a logical sequence through the planning / research / justification / implementation phases of the project.
- Ensure that your final upload contains a maximum of 1 jupyter notebook per module.
- Please ensure that additional resources are placed and linked to a logical file structure eg, Scripts, Images, Report, Data etc…
- Ensure that you include your raw and structured datasets in your submission
- 3000(+/- 10%) words in report (not including code, code comments, titles, references or citations)
- Your Word count MUST be included

(it is expected that research be carried out beyond class material)

Submission Requirements All assessment submissions must meet the minimum requirements listed below.
Failure to do so may have implications for the mark awarded.

All assessment submissions must:
- Jupyter Notebook, Word Document, Dashboard and version control address
- Be submitted by the deadline date specified or be subject to late submission penalties
- Be submitted via Moodle upload
- Use Harvard Referencing when citing third party material
- Be the student’s own work.
- Include the CCT assessment cover page.

In [41]:
import pandas as pd

In [42]:
df = pd.read_csv('Data/FAOSTAT_data_en_12-19-2022_IRL_SPA_crop_livestock_products.csv')

In [43]:
df.head()

,Domain Code,Domain,Area Code (ISO3),Area,Element Code,Element,Item Code (CPC),Item,Year Code,Year,Unit,Value,Flag,Flag Description
0,TCL,Crops and livestock products,IRL,Ireland,5610,Import Quantity,01929.07,"Abaca, manila hemp, raw",1961,1961,tonnes,NaN,O,Missing value
1,TCL,Crops and livestock products,IRL,Ireland,5610,Import Quantity,01929.07,"Abaca, manila hemp, raw",1962,1962,tonnes,NaN,O,Missing value
2,TCL,Crops and livestock products,IRL,Ireland,5610,Import Quantity,01929.07,"Abaca, manila hemp, raw",1963,1963,tonnes,NaN,O,Missing value
3,TCL,Crops and livestock products,IRL,Ireland,5610,Import Quantity,01929.07,"Abaca, manila hemp, raw",1964,1964,tonnes,NaN,O,Missing value
4,TCL,Crops and livestock products,IRL,Ireland,5610,Import Quantity,01929.07,"Abaca, manila hemp, raw",1965,1965,tonnes,NaN,O,Missing value

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 172266 entries, 0 to 172265
Data columns (total 14 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Domain Code       172266 non-null  object
 1   Domain            172266 non-null  object
 2   Area Code (ISO3)  172266 non-null  object
 3   Area              172266 non-null  object
 4   Element Code      172266 non-null  int64
 5   Element           172266 non-null  object
 6   Item Code (CPC)   172266 non-null  object
 7   Item              172266 non-null  object
 8   Year Code         172266 non-null  int64
 9   Year              172266 non-null  int64
 10  Unit              172266 non-null  object
 11  Value             164530 non-null  float64
 12  Flag              172266 non-null  object
 13  Flag Description  172266 non-null  object
dtypes: float64(1), int64(3), object(10)
memory usage: 18.4+ MB

In [45]:
df = df.dropna(subset=['Value'])

In [46]:
df['Item'].unique()

array(['Abaca, manila hemp, raw', 'Almonds, in shell', 'Almonds, shelled',
       'Animal oils and fats n.e.c.',
       'Animal or vegetable fats and oils and their fractions, chemically modified, except those hydrogenated, inter-esterified, re-esterified or elaidinized; inedible mixtures or preparations of animal or vegetable fats or oils',
       'Anise, badian, coriander, cumin, caraway, fennel and juniper berries, raw',
       'Apple juice', 'Apple juice, concentrated', 'Apples', 'Apricots',
       'Apricots, dried', 'Areca nuts', 'Artichokes', 'Asparagus',
       'Asses', 'Avocados', 'Bananas', 'Barley', 'Barley, pearled',
       'Beans, dry', 'beef and veal preparations nes',
       'Beer of barley, malted', 'Bees', 'Beeswax', 'Beet pulp',
       'Blueberries', 'Bran of maize', 'Bran of wheat',
       'Brazil nuts, shelled', 'Bread', 'Breakfast cereals',
       'Brewing or distilling dregs and waste',
       'Broad beans and horse beans, dry', 'Buckwheat', 'Buffalo',
       'Bulgur', 'Butter of cow milk',
       'Buttermilk, curdled and acidified milk', 'Cabbages',
       'Cake of  linseed', 'Cake of  soya beans', 'Cake of copra',
       'Cake of cottonseed', 'Cake of groundnuts', 'Cake of maize',
       'Cake of palm kernel', 'Cake of rapeseed', 'Cake of sesame seed',
       'Cake of sunflower seed', 'Camels', 'Canary seed',
       'Canned mushrooms', 'Cantaloupes and other melons',
       'Carrots and turnips', 'Cashew nuts, in shell',
       'Cashew nuts, shelled', 'Cassava, dry', 'Cattle',
       'Cattle fat, unrendered', 'Cauliflowers and broccoli',
       'Cereal preparations',
       'Cereal straw, husks, unprepared, ground, pressed, or in the form of pellets',
       'Cheese from milk of sheep, fresh or processed',
       'Cheese from whole cow milk', 'Cherries', 'Chestnuts, in shell',
       'Chick peas, dry', 'Chickens',
       'Chillies and peppers, dry (Capsicum spp., Pimenta spp.), raw',
       'Chillies and peppers, green (Capsicum spp. and Pimenta spp.)',
       'Chocolate products nes', 'Cider and other fermented beverages',
       'Cigarettes', 'Cigars and cheroots',
       'Cinnamon and cinnamon-tree flowers, raw',
       'Citrus juice, concentrated n.e.c.', 'Cloves (whole stems), raw',
       'Cocoa beans', 'Cocoa butter, fat and oil',
       'Cocoa paste not defatted', 'Cocoa powder and cake', 'Coconut oil',
       'Coconuts, desiccated', 'Coconuts, in shell', 'Coffee extracts',
       'Coffee husks and skins', 'Coffee substitutes',
       'Coffee, decaffeinated or roasted', 'Coffee, green', 'Coir, raw',
       'Communion wafers, empty cachets of a kind suitable for pharmaceutical use, sealing wafers, rice paper and similar products.',
       'Copra', 'Cotton lint, ginned', 'Cotton linters', 'Cotton seed',
       'Cotton waste', 'Cotton, carded or combed', 'Cottonseed oil',
       'Cranberries', 'Cream, fresh', 'Crude organic material n.e.c.',
       'Cucumbers and gherkins', 'Currants', 'Dairy products n.e.c.',
       'Dates', 'Dog or cat food, put up for retail sale', 'Ducks',
       'Edible offal of cattle, fresh, chilled or frozen',
       'Edible offal of pigs, fresh, chilled or frozen',
       'Edible offal of sheep, fresh, chilled or frozen',
       'Edible offals and liver of chickens and guinea fowl, fresh, chilled or frozen',
       'Edible offals and liver of ducks, fresh, chilled or frozen',
       'Edible offals and liver of geese, fresh, chilled or frozen',
       'Edible roots and tubers with high starch or inulin content, n.e.c., fresh',
       'Eggplants (aubergines)',
       'Eggs from other birds in shell, fresh, n.e.c.', 'Eggs, dried',
       'Eggs, liquid', 'Essential oils n.e.c.',
       'Extracts, essences and concentrates of tea or mate, and preparations with a basis thereof or with a basis of tea or maté',
       'Fat of pigs', 'Fat preparations n.e.c.',
       'Fatty liver preparations', 'Figs', 'Figs, dried',
       'Fine animal hair, n.e.c.', 'Flax, processed but not spun',
       'Flax, raw or retted', 'Flax, tow and waste',
       'Flour of cereals n.e.c.', 'Flour of maize',
       'Flour of mustard seed', 'Flour of pulses', 'Flour of rice',
       'Flour of roots and tubers n.e.c.',
       'Flour, meal, powder, flakes, granules and pellets of potatoes',
       'Fonio', 'Food preparations n.e.c.',
       'Food preparations of flour, meal or malt extract', 'Food wastes',
       'Fruit prepared n.e.c.', 'Game meat, fresh, chilled or frozen',
       'Germ of maize', 'Ginger, raw', 'Glucose and dextrose',
       'Gluten feed and meal', 'Goats', 'Grape juice', 'Grapefruit juice',
       'Grapefruit juice, concentrated', 'Grapes', 'Green corn (maize)',
       'Green garlic', 'Groundnut oil', 'Groundnuts, shelled',
       'Hazelnuts, in shell', 'Hazelnuts, shelled',
       'Hen eggs in shell, fresh', 'Hides, dry-salted of horses',
       'Hides, wet-salted of cattle',
       'Homogenized cooked fruit, prepared',
       'Homogenized vegetable preparations', 'Hop cones',
       'Horse meat, fresh or chilled', 'Horses', 'Husked rice',
       'Ice and snow', 'Ice cream and other edible ice',
       'Industrial monocarboxylic fatty acids; acid oils from refining',
       'Infant food', 'Juice of citrus fruit n.e.c.',
       'Juice of fruits n.e.c.', 'Juice of lemon',
       'Juice of pineapples, concentrated', 'Jute, raw or retted',
       'Karite nuts (sheanuts)', 'Kiwi fruit', 'Kola nuts', 'Lactose',
       'Leeks and other alliaceous vegetables',
       'Lemon juice, concentrated', 'Lemons and limes', 'Lentils, dry',
       'Lettuce and chicory', 'Linseed',
       'Lucerne (alfalfa) meal and pellets', 'Maize (corn)',
       'Malt, whether or not roasted', 'Mangoes, guavas and mangosteens',
       'Margarine and shortening', 'Maté leaves', 'Meat meal',
       'Meat of cattle boneless, fresh or chilled',
       'Meat of cattle with the bone, fresh or chilled',
       'Meat of chickens, fresh or chilled',
       'Meat of ducks, fresh or chilled',
       'Meat of geese, fresh or chilled',
       'Meat of goat, fresh or chilled',
       'Meat of pig boneless, fresh or chilled',
       'Meat of pig with the bone, fresh or chilled',
       'Meat of rabbits and hares, fresh or chilled',
       'Meat of sheep, fresh or chilled',
       'Meat of turkeys, fresh or chilled', 'Millet', 'Mixed grain',
       "Mixes and doughs for the preparation of bakers' wares",
       'Molasses', 'Mules and hinnies', 'Mushrooms and truffles',
       'Mustard seed', 'Natural honey', 'Natural rubber in other forms',
       'Natural rubber in primary forms', 'Nutmeg, mace, cardamoms, raw',
       'Oats', 'Oats, rolled', 'Oil of castor beans', 'Oil of linseed',
       'Oil of maize', 'Oil of olive residues', 'Oil of palm kernel',
       'Oil of sesame seed', 'Olive oil', 'Olives', 'Olives preserved',
       'Onions and shallots, dry (excluding dehydrated)',
       'Onions and shallots, green', 'Orange juice',
       'Orange juice, concentrated', 'Oranges', 'Other beans, green',
       'Other fibre crops, raw, n.e.c.', 'Other forage products, n.e.c.',
       'Other fructose and syrup', 'Other fruit n.e.c., dried',
       'Other fruits, n.e.c.', 'Other live animals non food, n.e.c.',
       'Other live animals, n.e.c.',
       'Other manufactured tobacco and manufactured tobacco substitutes; homogenized" or "reconstituted" tobacco; tobacco extracts and essences"',
       'Other meat and edible meat offal, salted, in brine, dried or smoked; edible flours and meals of meat or meat offal',
       'Other meat n.e.c. (excluding mammals), fresh, chilled or frozen',
       'Other non-alcoholic caloric beverages',
       'Other nuts (excluding wild edible nuts and groundnuts), in shell, n.e.c.',
       'Other oil of vegetable origin, crude n.e.c.',
       'Other oil seeds, n.e.c.',
       'Other raw skins of other animals, preserved',
       'Other stimulant, spice and aromatic crops, n.e.c.',
       'Other tropical fruits, n.e.c.',
       'Other vegetables provisionally preserved',
       'Other vegetables, fresh n.e.c.', 'Palm oil', 'Papayas',
       'Paste of tomatoes', 'Pastry', 'Peaches and nectarines',
       'Peanut butter', 'Pears', 'Peas, dry', 'Peas, green',
       'Pepper (Piper spp.), raw', 'Persimmons', 'Pig fat, rendered',
       'Pig meat preparations',
       'Pig meat, cuts, salted, dried or smoked (bacon and ham)',
       'Pineapple juice', 'Pineapples',
       'Pineapples, otherwise prepared or preserved',
       'Pistachios, in shell', 'Plantains and cooking bananas',
       'Plums and sloes', 'Plums, dried', 'Pomelos and grapefruits',
       'Poppy seed', 'Potatoes', 'Potatoes, frozen',
       'Poultry meat preparations', 'Prepared groundnuts',
       'Prepared nuts', 'Processed cheese',
       'Pulp, waste of fruit for feed', 'Pumpkins, squash and gourds',
       'Pyrethrum extract', 'Pyrethrum, dried flowers', 'Quinces',
       'Quinoa', 'Rabbits and hares', 'Raisins', 'Rape or colza seed',
       'Rapeseed or canola oil, crude',
       'Raw cane or beet sugar (centrifugal only)',
       'Raw hides and skins of sheep or lambs, with wool',
       'Raw milk of cattle', 'Raw silk (not thrown)',
       'Refined cane or beet sugar, in solid form, containing added flavouring or colouring matter; maple sugar and maple syrup',
       'Refined sugar', 'Residues of fatty substances', 'Rice',
       'Rice, broken', 'Rice, milled',
       'Rice, paddy (rice milled equivalent)', 'Rye',
       'Safflower-seed oil, crude',
       'Sausages and similar products of meat, offal or blood of beef and veal',
       'Sausages and similar products of meat, offal or blood of pig',
       'Sesame seed', 'Sheep',
       'Shorn wool, greasy, including fleece-washed shorn wool',
       'Silk waste', 'Silk-worm cocoons suitable for reeling',
       'Skim milk and whey powder', 'Skim milk of cows',
       'Skins, dry-salted of sheep', 'Skins, wet-salted of calves',
       'Sorghum', 'Sour cherries', 'Soya bean oil', 'Soya beans',
       'Soya sauce', 'Spinach', 'Starch of cassava', 'Strawberries',
       'Sugar and syrups n.e.c.', 'Sugar beet', 'Sugar confectionery',
       'Sunflower seed', 'Sunflower-seed oil, crude',
       'Sweet corn, frozen', 'Sweet corn, prepared or preserved',
       'Sweet potatoes', 'Swine / pigs', 'Tallow',
       'Tangerines, mandarins, clementines', 'Tea leaves', 'Tomato juice',
       'Tomatoes', 'Tomatoes, peeled (o/t vinegar)', 'Triticale',
       'Turkeys', 'Uncooked pasta, not stuffed or otherwise prepared',
       'Undenatured ethyl alcohol of an alcoholic strength by volume of less than 80% vol; spirits, liqueurs and other spirituous beverages',
       'Unmanufactured tobacco', 'Vanilla, raw',
       'Vegetable products for feed n.e.c.',
       'Vegetable products, fresh or dry n.e.c.',
       'Vegetable waxes (other than triglycerides), whether or not refined or coloured',
       'Vegetables frozen', 'Vegetables preserved (frozen)',
       'Vegetables preserved nes (o/t vinegar)', 'Vegetables, dehydrated',
       'Vegetables, pulses and potatoes, preserved by vinegar or acetic acid',
       'Vermouth and other wine of fresh grapes flavoured with plats or aromatic substances',
       'Walnuts, in shell', 'Walnuts, shelled', 'Watermelons', 'Wheat',
       'Wheat and meslin flour', 'Whey, condensed', 'Whey, dry',
       'Whole milk powder', 'Whole milk, condensed',
       'Whole milk, evaporated', 'Wine', 'Wool grease and lanolin',
       'Wool, degreased or carbonized, not carded or combed',
       'Wool, hair waste', 'Yoghurt, with additives',
       'Bambara beans, dry', 'Feed supplements', 'Flour of cassava',
       'Gooseberries', 'Oil of citronella', 'Skins, wet-salted of goats',
       'Skins, wet-salted of sheep', 'Yoghurt'], dtype=object)

In [47]:
df[df['Item']=='Turkeys']

,Domain Code,Domain,Area Code (ISO3),Area,Element Code,Element,Item Code (CPC),Item,Year Code,Year,Unit,Value,Flag,Flag Description
77436,TCL,Crops and livestock products,IRL,Ireland,5609,Import Quantity,02152,Turkeys,1961,1961,1000 Head,0.0,A,Official figure
77437,TCL,Crops and livestock products,IRL,Ireland,5609,Import Quantity,02152,Turkeys,1962,1962,1000 Head,0.0,A,Official figure
77438,TCL,Crops and livestock products,IRL,Ireland,5609,Import Quantity,02152,Turkeys,1963,1963,1000 Head,0.0,A,Official figure
77439,TCL,Crops and livestock products,IRL,Ireland,5609,Import Quantity,02152,Turkeys,1964,1964,1000 Head,0.0,A,Official figure
77440,TCL,Crops and livestock products,IRL,Ireland,5609,Import Quantity,02152,Turkeys,1965,1965,1000 Head,0.0,A,Official figure
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165329,TCL,Crops and livestock products,ESP,Spain,5922,Export Value,02152,Turkeys,2016,2016,1000 US$,143.0,A,Official figure
165330,TCL,Crops and livestock products,ESP,Spain,5922,Export Value,02152,Turkeys,2017,2017,1000 US$,172.0,A,Official figure
165331,TCL,Crops and livestock products,ESP,Spain,5922,Export Value,02152,Turkeys,2018,2018,1000 US$,118.0,A,Official figure
165332,TCL,Crops and livestock products,ESP,Spain,5922,Export Value,02152,Turkeys,2019,2019,1000 US$,129.0,A,Official figure
165333,TCL,Crops and livestock products,ESP,Spain,5922,Export Value,02152,Turkeys,2020,2020,1000 US$,99.0,A,Official figure

In [48]:
df['Element'].unique()

array(['Import Quantity', 'Import Value', 'Export Quantity',
       'Export Value'], dtype=object)

Getting new data

Okay. So. Let's look at poultry (meat) farming in Ireland (and Spain). In Ireland, let's see what factors affect chicken prices. I'm mainly going to look at feed and the price of grains. According to an EU factsheet on Irish agriculture, feeding stuff is by far the largest expense in agriculture, around five times the cost of the next largest expense, energy. (This is for all agriculture in Ireland though, so I'm sure cattle data is dominating these stats). Feed stuff for chicken is predominately maize, soya and wheat. Also maybe pig protein, but feeding chickens pigs was only made legal in the EU in Aug 2021 so I'm not going to look into it. Maize and soya are almost entirely imported. Feeding suppliers buy the grains from USA, Ukraine, Russia, etc, and then Irish poultry farmers buy their chicken feed from Irish feed suppliers. It is hard to find stats for feed supplies (especially to only relate to poultry) so I'm going to look at grain prices. Anyway, do grain prices have an impact on the consumer price of chicken? Also, what other factors affect the consumer price of chicken meat? Farm size? Intensive vs free range vs organic? Market demand? The price of imported cheap chicken from Brazil, Ukraine and Thailand, driven by fast food in Ireland's high demand for cheap chicken that the high prices of raw feed in Ireland can't meet (teagasc.ie). Apparently cheap imported chicken is undercutting European farmers (the guardian in their article about feeding animals to animals), let's see what's the truth of that.

What's the chicken consumpution per capita of Ireland vs Spain? Price of chicken relative to our gdp? Are we being screwed in our chicken price or is it line with our higher cost of living and wages in general?

In [11]:
from os import listdir
from os.path import isfile, join
FAOfiles = [f for f in listdir('./datasets/') if isfile(join('./datasets/', f))]

In [12]:
FAOfiles

['FAOSTAT_data_en_IRL_SPA_consumer_price_indices.csv',
 'FAOSTAT_data_en_IRL_SPA_crops_and_livestock_products_QCL.csv',
 'FAOSTAT_data_en_IRL_SPA_crops_and_livestock_products_TCL.csv',
 'FAOSTAT_data_en_IRL_SPA_production_indices.csv',
 'FAOSTAT_data_en_IRL_SPA_trade_indices.csv',
 'FAOSTAT_data_en_IRL_SPA_value_agri_production.csv',
 'FAOSTAT_data_en_structural_data_from_agri_census.csv',
 'FAOSTAT_data_en__IRL_SPA_producer_prices.csv']

In [13]:
df_dict = {}
for file in FAOfiles:
    df_dict[file[:-4]] = pd.read_csv('./datasets/'+file)

In [14]:
df_dict

{'FAOSTAT_data_en_IRL_SPA_consumer_price_indices':      Domain Code                  Domain  Area Code (M49)     Area  Year Code  \
 0             CP  Consumer Price Indices              372  Ireland       2000
 1             CP  Consumer Price Indices              372  Ireland       2000
 2             CP  Consumer Price Indices              372  Ireland       2000
 3             CP  Consumer Price Indices              372  Ireland       2000
 4             CP  Consumer Price Indices              372  Ireland       2000
 ...          ...                     ...              ...      ...        ...
 1609          CP  Consumer Price Indices              724    Spain       2022
 1610          CP  Consumer Price Indices              724    Spain       2022
 1611          CP  Consumer Price Indices              724    Spain       2022
 1612          CP  Consumer Price Indices              724    Spain       2022
 1613          CP  Consumer Price Indices              724    Spain       2022

       Year  Item Code                                        Item  \
 0     2000      23013  Consumer Prices, Food Indices (2015 = 100)
 1     2000      23013  Consumer Prices, Food Indices (2015 = 100)
 2     2000      23013  Consumer Prices, Food Indices (2015 = 100)
 3     2000      23013  Consumer Prices, Food Indices (2015 = 100)
 4     2000      23013  Consumer Prices, Food Indices (2015 = 100)
 ...    ...        ...                                         ...
 1609  2022      23014                        Food price inflation
 1610  2022      23014                        Food price inflation
 1611  2022      23014                        Food price inflation
 1612  2022      23014                        Food price inflation
 1613  2022      23014                        Food price inflation

       Months Code     Months Unit      Value Flag  \
 0            7001    January  NaN  87.551570    X
 1            7002   February  NaN  87.842760    X
 2            7003      March  NaN  88.036880    X
 3            7004      April  NaN  88.133950    X
 4            7005        May  NaN  89.395770    X
 ...           ...        ...  ...        ...  ...
 1609         7005        May    %  10.984332    E
 1610         7006       June    %  12.949015    E
 1611         7007       July    %  13.525500    E
 1612         7008     August    %  13.754012    E
 1613         7009  September    %  14.355534    E

                              Flag Description               Note
 0     Figure from international organizations  base year is 2015
 1     Figure from international organizations  base year is 2015
 2     Figure from international organizations  base year is 2015
 3     Figure from international organizations  base year is 2015
 4     Figure from international organizations  base year is 2015
 ...                                       ...                ...
 1609                          Estimated value                NaN
 1610                          Estimated value                NaN
 1611                          Estimated value                NaN
 1612                          Estimated value                NaN
 1613                          Estimated value                NaN

 [1614 rows x 15 columns],
 'FAOSTAT_data_en_IRL_SPA_crops_and_livestock_products_QCL':      Domain Code                        Domain  Area Code (M49)     Area  \
 0            QCL  Crops and livestock products              372  Ireland
 1            QCL  Crops and livestock products              372  Ireland
 2            QCL  Crops and livestock products              372  Ireland
 3            QCL  Crops and livestock products              372  Ireland
 4            QCL  Crops and livestock products              372  Ireland
 ...          ...                           ...              ...      ...
 2653         QCL  Crops and livestock products              724    Spain
 2654         QCL  Crops and livestock products              724    Spain
 2655         QCL  Crops and livestock products              724    Spain
 2656         QCL  Crops and livestock products              724    Spain
 2657         QCL  Crops and livestock products              724    Spain

       Element Code         Element  Item Code (CPC)    Item  Year Code  Year  \
 0             5312  Area harvested            115.0  Barley       1961  1961
 1             5312  Area harvested            115.0  Barley       1962  1962
 2             5312  Area harvested            115.0  Barley       1963  1963
 3             5312  Area harvested            115.0  Barley       1964  1964
 4             5312  Area harvested            115.0  Barley       1965  1965
 ...            ...             ...              ...     ...        ...   ...
 2653          5510      Production            111.0   Wheat       2017  2017
 2654          5510      Production            111.0   Wheat       2018  2018
 2655          5510      Production            111.0   Wheat       2019  2019
 2656          5510      Production            111.0   Wheat       2020  2020
 2657          5510      Production            111.0   Wheat       2021  2021

         Unit      Value Flag Flag Description
 0         ha   146373.0    A  Official figure
 1         ha   164219.0    A  Official figure
 2         ha   173608.0    A  Official figure
 3         ha   183644.0    A  Official figure
 4         ha   187790.0    A  Official figure
 ...      ...        ...  ...              ...
 2653  tonnes  4875957.0    A  Official figure
 2654  tonnes  8322510.0    A  Official figure
 2655  tonnes  6041170.0    A  Official figure
 2656  tonnes  8143510.0    A  Official figure
 2657  tonnes  8564630.0    A  Official figure

 [2658 rows x 14 columns],
 'FAOSTAT_data_en_IRL_SPA_crops_and_livestock_products_TCL':      Domain Code                        Domain  Area Code (M49)     Area  \
 0            TCL  Crops and livestock products              372  Ireland
 1            TCL  Crops and livestock products              372  Ireland
 2            TCL  Crops and livestock products              372  Ireland
 3            TCL  Crops and livestock products              372  Ireland
 4            TCL  Crops and livestock products              372  Ireland
 ...          ...                           ...              ...      ...
 8715         TCL  Crops and livestock products              724    Spain
 8716         TCL  Crops and livestock products              724    Spain
 8717         TCL  Crops and livestock products              724    Spain
 8718         TCL  Crops and livestock products              724    Spain
 8719         TCL  Crops and livestock products              724    Spain

       Element Code          Element Item Code (CPC)    Item  Year Code  Year  \
 0             5610  Import Quantity            0115  Barley       1961  1961
 1             5610  Import Quantity            0115  Barley       1962  1962
 2             5610  Import Quantity            0115  Barley       1963  1963
 3             5610  Import Quantity            0115  Barley       1964  1964
 4             5610  Import Quantity            0115  Barley       1965  1965
 ...            ...              ...             ...     ...        ...   ...
 8715          5922     Export Value            0111   Wheat       2017  2017
 8716          5922     Export Value            0111   Wheat       2018  2018
 8717          5922     Export Value            0111   Wheat       2019  2019
 8718          5922     Export Value            0111   Wheat       2020  2020
 8719          5922     Export Value            0111   Wheat       2021  2021

           Unit     Value Flag Flag Description
 0       tonnes    4544.0    A  Official figure
 1       tonnes    3182.0    A  Official figure
 2       tonnes    4845.0    A  Official figure
 3       tonnes     433.0    A  Official figure
 4       tonnes   80132.0    A  Official figure
 ...        ...       ...  ...              ...
 8715  1000 US$   76166.0    A  Official figure
 8716  1000 US$   96977.0    A  Official figure
 8717  1000 US$  145026.0    A  Official figure
 8718  1000 US$  180098.0    A  Official figure
 8719  1000 US$  133745.0    A  Official figure

 [8720 rows x 14 columns],
 'FAOSTAT_data_en_IRL_SPA_production_indices':       Domain Code              Domain  Area Code (M49)     Area  Element Code  \
 0              QI  Production Indices              372  Ireland           432
 1              QI  Production Indices              372  Ireland           432
 2              QI  Production Indices              372  Ireland           432
 3              QI  Production Indices              372  Ireland           432
 4              QI  Production Indices              372  Ireland           432
 ...           ...                 ...              ...      ...           ...
 18439          QI  Production Indices              724    Spain           434
 18440          QI  Production Indices              724    Spain           434
 18441          QI  Production Indices              724    Spain           434
 18442          QI  Production Indices              724    Spain           434
 18443          QI  Production Indices              724    Spain           434

                                                  Element Item Code (CPC)  \
 0        Gross Production Index Number (2014-2016 = 100)           01341
 1        Gross Production Index Number (2014-2016 = 100)           01341
 2        Gross Production Index Number (2014-2016 = 100)           01341
 3        Gross Production Index Number (2014-2016 = 100)           01341
 4        Gross Production Index Number (2014-2016 = 100)           01341
 ...                                                  ...             ...
 18439  Gross per capita Production Index Number (2014...           F2054
 18440  Gross per capita Production Index Number (2014...           F2054
 18441  Gross per capita Production Index Number (2014...           F2054
 18442  Gross per capita Production Index Number (2014...           F2054
 18443  Gross per capita Production Index Number (2014...           F2054

          Item  Year Code  Year   Unit   Value Flag Flag Description
 0      Apples       1961  1961  index  144.52    E  Estimated value
 1      Apples       1962  1962  index  154.49    E  Estimated value
 2      Apples       1963  1963  index  174.42    E  Estimated value
 3      Apples       1964  1964  index  119.60    E  Estimated value
 4      Apples       1965  1965  index  104.65    E  Estimated value
 ...       ...        ...   ...    ...     ...  ...              ...
 18439    Food       2016  2016  index  106.25    E  Estimated value
 18440    Food       2017  2017  index  101.75    E  Estimated value
 18441    Food       2018  2018  index  117.74    E  Estimated value
 18442    Food       2019  2019  index  106.58    E  Estimated value
 18443    Food       2020  2020  index  117.43    E  Estimated value

 [18444 rows x 14 columns],
 'FAOSTAT_data_en_IRL_SPA_trade_indices':      Domain Code         Domain  Area Code (M49)     Area  Element Code  \
 0             TI  Trade Indices              372  Ireland            64
 1             TI  Trade Indices              372  Ireland            64
 2             TI  Trade Indices              372  Ireland            64
 3             TI  Trade Indices              372  Ireland            64
 4             TI  Trade Indices              372  Ireland            64
 ...          ...            ...              ...      ...           ...
 8907          TI  Trade Indices              724    Spain           495
 8908          TI  Trade Indices              724    Spain           495
 8909          TI  Trade Indices              724    Spain           495
 8910          TI  Trade Indices              724    Spain           495
 8911          TI  Trade Indices              724    Spain           495

                                       Element  Item Code (CPC)    Item  \
 0           Import Value Base Period Quantity            115.0  Barley
 1           Import Value Base Period Quantity            115.0  Barley
 2           Import Value Base Period Quantity            115.0  Barley
 3           Import Value Base Period Quantity            115.0  Barley
 4           Import Value Base Period Quantity            115.0  Barley
 ...                                       ...              ...     ...
 8907  Export Quantity Index (2014-2016 = 100)            111.0   Wheat
 8908  Export Quantity Index (2014-2016 = 100)            111.0   Wheat
 8909  Export Quantity Index (2014-2016 = 100)            111.0   Wheat
 8910  Export Quantity Index (2014-2016 = 100)            111.0   Wheat
 8911  Export Quantity Index (2014-2016 = 100)            111.0   Wheat

       Year Code  Year    Unit  Value Flag Flag Description
 0          1961  1961  1000 $   4433    E  Estimated value
 1          1962  1962  1000 $   4801    E  Estimated value
 2          1963  1963  1000 $   4706    E  Estimated value
 3          1964  1964  1000 $   4704    E  Estimated value
 4          1965  1965  1000 $   3901    E  Estimated value
 ...         ...   ...     ...    ...  ...              ...
 8907       2017  2017   index     66    E  Estimated value
 8908       2018  2018   index     83    E  Estimated value
 8909       2019  2019   index    129    E  Estimated value
 8910       2020  2020   index    132    E  Estimated value
 8911       2021  2021   index     75    E  Estimated value

 [8912 rows x 14 columns],
 'FAOSTAT_data_en_IRL_SPA_value_agri_production':      Domain Code                            Domain  Area Code (M49)     Area  \
 0             QV  Value of Agricultural Production              372  Ireland
 1             QV  Value of Agricultural Production              372  Ireland
 2             QV  Value of Agricultural Production              372  Ireland
 3             QV  Value of Agricultural Production              372  Ireland
 4             QV  Value of Agricultural Production              372  Ireland
 ...          ...                               ...              ...      ...
 2806          QV  Value of Agricultural Production              724    Spain
 2807          QV  Value of Agricultural Production              724    Spain
 2808          QV  Value of Agricultural Production              724    Spain
 2809          QV  Value of Agricultural Production              724    Spain
 2810          QV  Value of Agricultural Production              724    Spain

       Element Code                                            Element  \
 0              152  Gross Production Value (constant 2014-2016 tho...
 1              152  Gross Production Value (constant 2014-2016 tho...
 2              152  Gross Production Value (constant 2014-2016 tho...
 3              152  Gross Production Value (constant 2014-2016 tho...
 4              152  Gross Production Value (constant 2014-2016 tho...
 ...            ...                                                ...
 2806            58  Gross Production Value (constant 2014-2016 tho...
 2807            58  Gross Production Value (constant 2014-2016 tho...
 2808            58  Gross Production Value (constant 2014-2016 tho...
 2809            58  Gross Production Value (constant 2014-2016 tho...
 2810            58  Gross Production Value (constant 2014-2016 tho...

      Item Code (CPC)    Item  Year Code  Year         Unit    Value Flag  \
 0               0115  Barley       1961  1961  1000 Int. $   100413    E
 1               0115  Barley       1962  1962  1000 Int. $   117519    E
 2               0115  Barley       1963  1963  1000 Int. $   114733    E
 3               0115  Barley       1964  1964  1000 Int. $   107291    E
 4               0115  Barley       1965  1965  1000 Int. $   119960    E
 ...              ...     ...        ...   ...          ...      ...  ...
 2806            0111   Wheat       2016  2016     1000 US$  1812197    E
 2807            0111   Wheat       2017  2017     1000 US$  1122322    E
 2808            0111   Wheat       2018  2018     1000 US$  1915631    E
 2809            0111   Wheat       2019  2019     1000 US$  1390525    E
 2810            0111   Wheat       2020  2020     1000 US$  1874430    E

      Flag Description
 0     Estimated value
 1     Estimated value
 2     Estimated value
 3     Estimated value
 4     Estimated value
 ...               ...
 2806  Estimated value
 2807  Estimated value
 2808  Estimated value
 2809  Estimated value
 2810  Estimated value

 [2811 rows x 14 columns],
 'FAOSTAT_data_en_structural_data_from_agri_census':     Domain Code                                      Domain  Area Code (M49)  \
 0          WCAD  Structural data from agricultural censuses              372
 1          WCAD  Structural data from agricultural censuses              372
 2          WCAD  Structural data from agricultural censuses              372
 3          WCAD  Structural data from agricultural censuses              372
 4          WCAD  Structural data from agricultural censuses              372
 ..          ...                                         ...              ...
 263        WCAD  Structural data from agricultural censuses              724
 264        WCAD  Structural data from agricultural censuses              724
 265        WCAD  Structural data from agricultural censuses              724
 266        WCAD  Structural data from agricultural censuses              724
 267        WCAD  Structural data from agricultural censuses              724

         Area  Element Code                      Element  Item Code  \
 0    Ireland         50260                         Area      27002
 1    Ireland          5017                 Average area      27002
 2    Ireland         60850                       Number      27002
 3    Ireland         50260                         Area      27002
 4    Ireland          5017                 Average area      27002
 ..       ...           ...                          ...        ...
 263    Spain         60851                       Number     270090
 264    Spain         60851                       Number      27010
 265    Spain          5019  Average persons per holding      27010
 266    Spain         60851                       Number      27010
 267    Spain          5019  Average persons per holding      27010

                                                  Item  WCA Round  Census Year  \
 0                                            Holdings       1930         1929
 1                                            Holdings       1930         1929
 2                                            Holdings       1930         1929
 3                                            Holdings       1950         1949
 4                                            Holdings       1950         1949
 ..                                                ...        ...          ...
 263  Household members, engaged in agriculture, total       2010         2009
 264                           Hired permanent workers       2000         1999
 265                           Hired permanent workers       2000         1999
 266                           Hired permanent workers       2010         2009
 267                           Hired permanent workers       2010         2009

         Unit       Value Flag Flag Description  \
 0         ha  6199000.00    A  Official figure
 1         ha       17.76    E  Estimated value
 2         No   349000.00    A  Official figure
 3         ha  5873000.00    A  Official figure
 4         ha       15.48    E  Estimated value
 ..       ...         ...  ...              ...
 263  persons  1089900.00    A  Official figure
 264  persons   211731.00    A  Official figure
 265  persons        0.12    E  Estimated value
 266  persons   275260.00    A  Official figure
 267  persons        0.28    E  Estimated value

                                                   Note

In [16]:
print(df_dict.keys())

dict_keys(['FAOSTAT_data_en_IRL_SPA_consumer_price_indices', 'FAOSTAT_data_en_IRL_SPA_crops_and_livestock_products_QCL', 'FAOSTAT_data_en_IRL_SPA_crops_and_livestock_products_TCL', 'FAOSTAT_data_en_IRL_SPA_production_indices', 'FAOSTAT_data_en_IRL_SPA_trade_indices', 'FAOSTAT_data_en_IRL_SPA_value_agri_production', 'FAOSTAT_data_en_structural_data_from_agri_census', 'FAOSTAT_data_en__IRL_SPA_producer_prices'])

In [17]:
df_dict['FAOSTAT_data_en_IRL_SPA_crops_and_livestock_products_QCL']

,Domain Code,Domain,Area Code (M49),Area,Element Code,Element,Item Code (CPC),Item,Year Code,Year,Unit,Value,Flag,Flag Description
0,QCL,Crops and livestock products,372,Ireland,5312,Area harvested,115.0,Barley,1961,1961,ha,146373.0,A,Official figure
1,QCL,Crops and livestock products,372,Ireland,5312,Area harvested,115.0,Barley,1962,1962,ha,164219.0,A,Official figure
2,QCL,Crops and livestock products,372,Ireland,5312,Area harvested,115.0,Barley,1963,1963,ha,173608.0,A,Official figure
3,QCL,Crops and livestock products,372,Ireland,5312,Area harvested,115.0,Barley,1964,1964,ha,183644.0,A,Official figure
4,QCL,Crops and livestock products,372,Ireland,5312,Area harvested,115.0,Barley,1965,1965,ha,187790.0,A,Official figure
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2653,QCL,Crops and livestock products,724,Spain,5510,Production,111.0,Wheat,2017,2017,tonnes,4875957.0,A,Official figure
2654,QCL,Crops and livestock products,724,Spain,5510,Production,111.0,Wheat,2018,2018,tonnes,8322510.0,A,Official figure
2655,QCL,Crops and livestock products,724,Spain,5510,Production,111.0,Wheat,2019,2019,tonnes,6041170.0,A,Official figure
2656,QCL,Crops and livestock products,724,Spain,5510,Production,111.0,Wheat,2020,2020,tonnes,8143510.0,A,Official figure
2657,QCL,Crops and livestock products,724,Spain,5510,Production,111.0,Wheat,2021,2021,tonnes,8564630.0,A,Official figure

In [18]:
df_dict['FAOSTAT_data_en_IRL_SPA_crops_and_livestock_products_QCL']['Element'].unique()

array(['Area harvested', 'Yield', 'Production', 'Stocks',
       'Yield/Carcass Weight', 'Producing Animals/Slaughtered'],
      dtype=object)

In [19]:
df_dict['FAOSTAT_data_en_IRL_SPA_crops_and_livestock_products_QCL']['Unit'].unique()

array(['ha', 'hg/ha', 'tonnes', '1000 Head', '0.1g/An'], dtype=object)

Unit translation \[I have a natural inclination for SI units\]:

- ha = hectare (area) = 10000 m$^2$
- hg/ha = hectogram/hectare (yield of cereal) = 0.1 kg / 10000 m$^2$
- tonnes = 1000 kg
- 1000 Head = I don't know exactly but it's some kind of animal unit
- 0.1g/An = 0.1 g per animal

In [23]:
df_dict['FAOSTAT_data_en_IRL_SPA_crops_and_livestock_products_QCL'][df_dict['FAOSTAT_data_en_IRL_SPA_crops_and_livestock_products_QCL']['Unit']== '1000 Head']['Element'].unique()

array(['Stocks', 'Producing Animals/Slaughtered'], dtype=object)

In [24]:
df_dict['FAOSTAT_data_en_IRL_SPA_crops_and_livestock_products_QCL']['Item'].unique()

array(['Barley', 'Cereals n.e.c.', 'Chickens', 'Maize (corn)',
       'Meat of chickens, fresh or chilled', 'Mixed grain', 'Oats',
       'Soya beans', 'Sunflower seed', 'Wheat', 'Millet'], dtype=object)

In [30]:
items = df_dict['FAOSTAT_data_en_IRL_SPA_crops_and_livestock_products_QCL']['Item'].unique()

In [31]:
items

array(['Barley', 'Cereals n.e.c.', 'Chickens', 'Maize (corn)',
       'Meat of chickens, fresh or chilled', 'Mixed grain', 'Oats',
       'Soya beans', 'Sunflower seed', 'Wheat', 'Millet'], dtype=object)

In [32]:
chicken_item = []
grains_item = []
for item in items:
    if 'hicken' in item:
        chicken_item.append(item)
    else:
        grains_item.append(item)

In [34]:
print('Chicken list: ', chicken_item)
print('Grains list: ', grains_item)

Chicken list:  ['Chickens', 'Meat of chickens, fresh or chilled']
Grains list:  ['Barley', 'Cereals n.e.c.', 'Maize (corn)', 'Mixed grain', 'Oats', 'Soya beans', 'Sunflower seed', 'Wheat', 'Millet']

In [49]:
df_dict['FAOSTAT_data_en_IRL_SPA_crops_and_livestock_products_QCL'].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2658 entries, 0 to 2657
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Domain Code       2658 non-null   object
 1   Domain            2658 non-null   object
 2   Area Code (M49)   2658 non-null   int64
 3   Area              2658 non-null   object
 4   Element Code      2658 non-null   int64
 5   Element           2658 non-null   object
 6   Item Code (CPC)   2658 non-null   float64
 7   Item              2658 non-null   object
 8   Year Code         2658 non-null   int64
 9   Year              2658 non-null   int64
 10  Unit              2658 non-null   object
 11  Value             2658 non-null   float64
 12  Flag              2658 non-null   object
 13  Flag Description  2658 non-null   object
dtypes: float64(2), int64(4), object(8)
memory usage: 290.8+ KB